export { default as Navbar } from "./Navbar";
export { default as Header } from "./Header";
export { default as Testimonial } from "./Testimonial";
export { default as Team } from "./Team";
export { default as Projects } from "./Projects";
export { default as WhatWeDo } from "./WhatWeDo";
export { default as Blog } from "./Blog";
export { default as About } from "./About";
export { default as Footer } from "./Footer";
